### ISSUE TITLE
Example code doesn't compile

### ISSUE THREAD

**Issue by c4s4** [jinzhu/configor#2]
I would rather replace with an example that compiles and works:

```go
package main

import (
	"fmt"
	"github.com/jinzhu/configor"
)

var Config = struct {
	APPName string `default:"app name"`

	DB struct {
		Name     string
		User     string `default:"root"`
		Password string `required:"true" env:"DBPassword"`
		Port     uint   `default:"3306"`
	}

	Contacts []struct {
		Name  string
		Email string `required:"true"`
	}
}{}

func main() {
	configor.Load(&Config, "config.yml")
	fmt.Printf("config: %#v", Config)
}
```

I would also give a corresponding example configuration file, such as *config.yml*:

```yaml
APPName: test

DB:
    Name:     test
    User:     test
    Password: test
    Port:     1234

Contacts:
- Name: i test
  Email: test@test.com
```
