### ISSUE TITLE
empty values

### ISSUE THREAD

**Issue by sundowndev** [jinzhu/configor#52]
```go
var Config = struct {
	Contacts []struct {
		Name  string
		Email string `required:"true"`
	}
}{}

configor.Load(&Config, "config.yml")
fmt.Println(Config)
// log: {[]}
```

```yaml
contacts:
- name: i test
email: test@test.com
```
