### ISSUE TITLE
Map type cause error "already set in map" with ErrorOnUnmatchedKeys, multiple YAML overlays

### ISSUE THREAD

**Issue by xmlking** [jinzhu/configor#56]
I am using following structs and enabled `ErrorOnUnmatchedKeys`

Got Error
`
yaml: unmarshal errors:\n  line 21: key \"account\" already set in map\n  line 24: key \"greeter\" already set in map\n  line 27: key \"emailer\" already set in map\n  line 30: key \"recorder\" already set in map
`

```go
type Service struct {
	Endpoint             string   `yaml:"endpoint,omitempty"`
	Version              string   `yaml:"version,omitempty" default:"v0.1.0"`
	Deadline             uint32   `yaml:",omitempty" default:"1000000"`
}

type Configuration struct {
	Services             map[string]*Service   
}
```

**config.yaml**
```yaml
services:
  account:
    endpoint: mkit.service.account
    version: v0.1.0
  greeter:
    endpoint: mkit.service.greeter
    version: v0.1.0
  emailer:
    endpoint: mkit.service.emailer
    version: v0.1.0
  recorder:
    endpoint: mkit.service.recorder
    version: v0.1.0
```

**config.development.yaml**
```yaml
services:
  account:
    endpoint: mkit.service.account
    version: v0.2.0
  greeter:
    endpoint: mkit.service.greeter
    version: v0.2.0
```
