### ISSUE TITLE
doesn't support camel, or _ - split style field name in yml file

### ISSUE THREAD

**Issue by yufenghui** [jinzhu/configor#62]
``` yml
server:
  id: 1
  name: ''

db:
  driverName: mysql
  url: ''
  demoDb: ''
  dataDb: ''
```

``` golang
var Config = struct {
	Server struct {
		Id   int    `required:"true"`
		Name string `required:"true"`
	}

	DB struct {
		DriverName string `required:"true"`
		Url      string `required:"true"`
		DemoDb  string `required:"true"`
		DataDb      string `required:"true"`
	}
}
```
