### ISSUE TITLE
Specify env var name in .yml file instead of go struct

### ISSUE THREAD

**Issue by nmapx** [jinzhu/configor#65]
## Is there a way to use env var specified as a value in .yml file? I would prefer configor to do it dynamically.

```yml
test:
  some_setting: "THIS_IS_MY_ENV_VAR"
  some_other_setting: "YET_ANOTHER_ENV_VAR"
```
```go
var Config = struct {
	Test struct {
		SomeSetting      string
		SomeOtherSetting string
	}
}{}
```

I've got multiple .yml config files which fits exactly the same struct (pattern). I want to avoid duplicating struct definition in Go, so it would be much better to have the ability to load env variables by what was specified in .yml file directly (env var name as a value). Is it possible?

I can accept any format. Something like this would work great (it's just an example, it doesn't work... yet 😄)
```yml
test:
  some_setting: "env.THIS_IS_MY_ENV_VAR"
  some_other_setting: "env.YET_ANOTHER_ENV_VAR"
```

## Expected answer

Well, it's a simple question. Please let me know how to achieve my goal 😄
