### ISSUE TITLE
无法正常读取yaml文件

### ISSUE THREAD

**Issue by forrestsun** [jinzhu/configor#7]
根据readme中的代码原样拷贝至代码文件，解析时仅得到了默认值，请问可能的原因是什么？

``` bash
config: struct { APPName string "default:\"app name\""; DB struct { Name string; User string "default:\"root\""; Password string "required:\"true\" env:\"DBPassword\""; Port uint "default:\"3306\"" }; Contacts []struct { Name string; Email string "required:\"true\"" } }{APPName:"app name", DB:struct { Name string; User string "default:\"root\""; Password string "required:\"true\" env:\"DBPassword\""; Port uint "default:\"3306\"" }{Name:"", User:"root", Password:"", Port:0x0}, Contacts:[]struct { Name string; Email string "required:\"true\"" }(nil)}
```

config.yml未做改

``` yaml
APPName: test

DB:
    Name:     test
    User:     test
    Password: test
    Port:     1234

Contacts:
- Name: i test
  Email: test@test.com
```

是格式的原因吗？

**Comment by forrestsun** [comment]
``` go
package main

import (
	"fmt"
	"github.com/jinzhu/configor"
)

type DB struct {
	Name     string `yaml:"Name"`
	User     string `yaml:"User"`
	Password string `yaml:"Password"`
	Port     string `yaml:"Port"`
}

var Config = struct {
	APPName string `yaml:"APPName"`
	DB      DB     `yaml:"DB"`
}{}

func main() {
	configor.Load(&Config, "config.yml")
	fmt.Printf("config: %#v", Config)
}

```

config.yml
``` yaml
APPName: test
DB:
  Name: test
  User: test
  Password: test
  Port: 1234
```
结果
```
config: struct { APPName string "yaml:\"APPName\""; DB main.DB "yaml:\"DB\"" }{APPName:"test", DB:main.DB{Name:"test", User:"test", Password:"test", Port:"1234"}}
```
现在读取的结果是正常的，请问是什么原因？
谢谢！
